routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('dashboard.index');
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');

    Route::get('/password', [App\Http\Controllers\PasswordController::class, 'edit'])->name('password.edit');
    Route::patch('/password', [App\Http\Controllers\PasswordController::class, 'updatePassword'])->name('password.updatePassword');

    //Roles Route
    Route::get('/roles/select', [App\Http\Controllers\RoleController::class, 'select'])->name('roles.select');
    Route::resource('/roles', \App\Http\Controllers\RoleController::class);

    //User Route
    Route::resource('/users', \App\Http\Controllers\UserController::class);

    //Category Post Route
    Route::get('/categories-post/select', [App\Http\Controllers\CategoriesPostController::class, 'select'])->name('categoriespost.select');
    Route::resource('/categories-post', App\Http\Controllers\CategoriesPostController::class);

    //Tag Post Route
    Route::get('/tags/select', [App\Http\Controllers\TagController::class, 'select'])->name('tags.select');
    Route::resource('/tags', App\Http\Controllers\TagController::class);

    //Post Route
    Route::resource('/posts', App\Http\Controllers\PostController::class);

    //File Manager Route 
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
   
});

app/Models/Tag.php
<?php

namespace App\Models;

use DigitalCloud\Blameable\Traits\Blameable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    use Blameable;
    protected $table = 'post_tags';
    protected $fillable = ['tag_title', 'tag_slug', 'is_active'];

    public function scopeSearch($query, $title)
    {
        return $query->where('tag_title', 'LIKE', "%{$title}%");
    }

    public function getRouteKeyName()
    {
        return 'tag_slug';
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class TagController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:Tag Show', ['only' => 'index']);
        $this->middleware('permission:Tag Create', ['only' => ['create', 'store']]);
        $this->middleware('permission:Tag Update', ['only' => ['edit', 'update']]);
        $this->middleware('permission:Tag Delete', ['only' => 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tags = [];
        if ($request->get('keyword')) {
            $tags = Tag::search($request->keyword)->orderBy('tag_title', 'asc')->paginate(10);
        } else {
            $tags = Tag::orderBy('tag_title', 'asc')->paginate(10);
        }
        return view('tags.index', [
            'tags' => $tags
        ]);
    }

    public function select(Request $request)
    {
        $tags = [];
        if ($request->has('q')) {
            $tags = Tag::select('id', 'tag_title')->search($request->q)->get();
        } else {
            $tags = Tag::select('id', 'tag_title')->limit(10)->get();
        }

        return response()->json($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $statuses = $this->statuses();
        return view('tags.create', compact('statuses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'tag_title' => 'required|string|max:60',
            'tag_slug' => 'required|string|unique:post_tags,tag_slug',
        ]);
        Tag::create([
            'tag_title' => $request->tag_title,
            'tag_slug' => $request->tag_slug,
            'is_active' => ($request->is_active) ? '1' : '0',
        ]);
        Alert::success('Add Tag', 'Added Tag Success');
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        return view('tags.show', compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        $statuses = $this->statuses();
        return view('tags.edit', compact('tag', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $request->validate([
            'tag_title' => 'required|string|max:60',
            'tag_slug' => 'required|string|unique:post_tags,tag_slug,' . $tag->id,
        ]);

        $tag->update([
            'tag_title' => $request->tag_title,
            'tag_slug' => $request->tag_slug,
            'is_active' => ($request->is_active) ? '1' : '0',
        ]);
        Alert::success('Update Tag', 'Updated Tag Success');
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        try {
            $tag->delete();
            Alert::success('Delete Tag', 'Delete Tag Success');
        } catch (\Throwable $th) {
            Alert::error('Delete Tag', 'Error' . $th->getMessage());
        }
        return redirect()->back();
    }

    private function statuses()
    {
        return [
            '0' => 'Draft',
            '1' => 'Published',
        ];
    }
}

resources/views/tags/create.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
          {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
          {{ Breadcrumbs::render('add_tag') }}
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
          <div class="pe-md-3 d-flex align-items-center">
              <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                  <i class='bx bx-log-out'></i>
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
              </form>
          </div>
          <div class="user-setting">
              <div class="imgBox">
                  <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
              </div>
          </div>
      </div>
  </div>
</nav>
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
      <div class="card">
          <div class="card-body _card-body">
              <form action="{{ route('tags.store') }}" method="POST">
                  @csrf
                  <div class="row">
                      <div class="col-md-3"></div>
                      <div class="col-md-6">
                          <!-- title -->
                          <div class="form-group _form-group">
                              <label for="input_tag_title" class="font-weight-bold">
                                  Name <span class="wajib">*</span>
                              </label>
                              <input id="input_tag_title" value="{{ old('tag_title') }}" name="tag_title" type="text" class="form-control @error('tag_title') is-invalid @enderror" placeholder="Write name here.." />
                              @error('tag_title')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                              @enderror
                          </div>
                          <!-- slug -->
                          <div class="form-group _form-group">
                              <label for="input_tag_slug" class="font-weight-bold">
                                  Slug
                              </label>
                              <input id="input_tag_slug" value="{{ old('tag_slug') }}" name="tag_slug" type="text" class="form-control @error('tag_slug') is-invalid @enderror" placeholder="Auto Generate" readonly />
                              @error('tag_slug')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                              @enderror
                          </div>

                          <!-- status -->
                          <div class="form-group{{ $errors->has('is_active') ? ' has-error' : '' }} _form-group">
                              <label for="input_post_status" class="font-weight-bold">
                                  Status
                              </label>
                              <div class="form-group">
                                  <label class="switch">
                                      <input type="checkbox" name="is_active" {{ old('is_active') == 1 ? 'checked' : null }}>
                                      <span class="slider-switch round"></span>
                                  </label>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3"></div>

                  </div>

                  <div class="row">
                      <div class="col-md-3"></div>
                      <div class="col-md-6">
                          <button type="submit" class="btn btn-primary _btn-primary float-right px-4">
                              Save
                          </button>
                          <div class="float-right">
                              <a class="btn btn-outline-secondary _btn-secondary px-4 mx-2" href="{{ route('tags.index') }}">
                                  Back
                              </a>
                          </div>
                      </div>
                      <div class="col-md-3"></div>
                  </div>

              </form>
          </div>
      </div>
  </div>
</div>
@endsection

@push('javascript-external')
<script src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
@endpush

@push('javascript-internal')
<script>
  $(document).ready(function() {
      $("#input_tag_title").change(function(event) {
          $("#input_tag_slug").val(
              event.target.value
              .trim()
              .toLowerCase()
              .replace(/[^a-z\d-]/gi, "-")
              .replace(/-+/g, "-")
              .replace(/^-|-$/g, "")
          );
      });

      $('#button_banner_image').filemanager('image');

      $("#input_banner_description").tinymce({
          relative_urls: false,
          language: "en",
          plugins: [
              "advlist autolink lists link image charmap print preview hr anchor pagebreak",
              "searchreplace wordcount visualblocks visualchars code fullscreen",
              "insertdatetime media nonbreaking save table directionality",
              "emoticons template paste textpattern",
          ],
          toolbar1: "fullscreen preview",
          toolbar2: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",

          file_picker_callback: function(callback, value, meta) {
              let x = window.innerWidth || document.documentElement.clientWidth || document
                  .getElementsByTagName('body')[0].clientWidth;
              let y = window.innerHeight || document.documentElement.clientHeight || document
                  .getElementsByTagName('body')[0].clientHeight;

              let cmsURL =
                  "{{ route('unisharp.lfm.show') }}" +
                  '?editor=' + meta.fieldname;
              if (meta.filetype == 'image') {
                  cmsURL = cmsURL + "&type=Images";
              } else {
                  cmsURL = cmsURL + "&type=Files";
              }

              tinyMCE.activeEditor.windowManager.openUrl({
                  url: cmsURL,
                  title: 'Filemanager',
                  width: x * 0.8,
                  height: y * 0.8,
                  resizable: "yes",
                  close_previous: "no",
                  onMessage: (api, message) => {
                      callback(message.content);
                  }
              });
          }
      });
      //select2 tag

  });
</script>
@endpush

resources/views/tags/edit.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
          {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
          {{ Breadcrumbs::render('detail_tag', $tag) }}
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
          <div class="pe-md-3 d-flex align-items-center">
              <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                  <i class='bx bx-log-out'></i>
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
              </form>
          </div>
          <div class="user-setting">
              <div class="imgBox">
                  <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
              </div>
          </div>
      </div>
  </div>
</nav>
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
      <div class="card">
          <div class="card-body -card-body">
              <form action="{{ route('tags.update', ['tag' => $tag]) }}" method="POST">
                  @csrf
                  @method('PUT')
                  <div class="row">
                      <div class="col-md-3"></div>
                      <div class="col-md-6">
                          <!-- title -->
                          <div class="form-group _form-group">
                              <label for="input_tag_title" class="font-weight-bold">
                                  Name <span class="wajib">* </span>
                              </label>
                              <input id="input_tag_title" value="{{ old('tag_title', $tag->tag_title) }}" name="tag_title" type="text" class="form-control @error('tag_title') is-invalid @enderror" placeholder="" />
                              @error('tag_title')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                              @enderror
                          </div>
                          <!-- slug -->
                          <div class="form-group _form-group">
                              <label for="input_tag_slug" class="font-weight-bold">
                                  Slug
                              </label>
                              <input id="input_tag_slug" value="{{ old('tag_slug', $tag->tag_slug) }}" name="tag_slug" type="text" class="form-control @error('tag_slug') is-invalid @enderror" placeholder="" readonly />
                              @error('tag_slug')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                              @enderror
                          </div>

                          <!-- status -->
                          <div class="form-group{{ $errors->has('is_active') ? ' has-error' : '' }} _form-group">
                              <label for="input_banner_status" class="font-weight-bold">
                                  Status
                              </label>
                              <div class="form-group">
                                  <label class="switch">
                                      <input type="checkbox" name="is_active" {{ old('is_active', $tag->is_active) == 1 ? 'checked' : null }}>
                                      <span class="slider-switch round"></span>
                                  </label>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-3"></div>
                  </div>

                  <div class="row">
                      <div class="col-md-3"></div>
                      <div class="col-md-6">
                          <button type="submit" class="btn btn-primary _btn-primary float-right px-4">
                              Update
                          </button>
                          <div class="float-right">
                              <a class="btn btn-outline-secondary _btn-secondary px-4 mx-2" href="{{ route('tags.index') }}">
                                  Back
                              </a>
                          </div>
                      </div>
                      <div class="col-md-3"></div>
                  </div>


              </form>
          </div>
      </div>
  </div>
</div>
@endsection

@push('javascript-external')
<script src="{{ asset('vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
@endpush

@push('javascript-internal')
<script>
  $(document).ready(function() {
      $("#input_tag_title").change(function(event) {
          $("#input_tag_slug").val(
              event.target.value
              .trim()
              .toLowerCase()
              .replace(/[^a-z\d-]/gi, "-")
              .replace(/-+/g, "-")
              .replace(/^-|-$/g, "")
          );
      });

      $('#button_banner_image').filemanager('image');

      $("#input_banner_description").tinymce({
          relative_urls: false,
          language: "en",
          plugins: [
              "advlist autolink lists link image charmap print preview hr anchor pagebreak",
              "searchreplace wordcount visualblocks visualchars code fullscreen",
              "insertdatetime media nonbreaking save table directionality",
              "emoticons template paste textpattern",
          ],
          toolbar1: "fullscreen preview",
          toolbar2: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",

          file_picker_callback: function(callback, value, meta) {
              let x = window.innerWidth || document.documentElement.clientWidth || document
                  .getElementsByTagName('body')[0].clientWidth;
              let y = window.innerHeight || document.documentElement.clientHeight || document
                  .getElementsByTagName('body')[0].clientHeight;

              let cmsURL =
                  "{{ route('unisharp.lfm.show') }}" +
                  '?editor=' + meta.fieldname;
              if (meta.filetype == 'image') {
                  cmsURL = cmsURL + "&type=Images";
              } else {
                  cmsURL = cmsURL + "&type=Files";
              }

              tinyMCE.activeEditor.windowManager.openUrl({
                  url: cmsURL,
                  title: 'Filemanager',
                  width: x * 0.8,
                  height: y * 0.8,
                  resizable: "yes",
                  close_previous: "no",
                  onMessage: (api, message) => {
                      callback(message.content);
                  }
              });
          }
      });
      //select2 tag

  });
</script>
@endpush

resources/views/tags/index.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
          {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
          {{ Breadcrumbs::render('tags') }}
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
          <div class="pe-md-3 d-flex align-items-center">
              <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                  <i class='bx bx-log-out'></i>
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
              </form>
          </div>
          <div class="user-setting">
              <div class="imgBox">
                  <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
              </div>
          </div>
      </div>
  </div>
</nav>
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
      <div class="card">
          <div class="card-header">
              <div class="row">
                  <div class="col-md-6">
                      <form action="{{ route('tags.index') }}" method="GET">
                          <div class="input-group">
                              <input name="keyword" value="{{ request()->get('keyword') }}" type="search" class="form-control" style="height: 40px;" placeholder="Search for tag..">
                              <div class="input-group-append">
                                  <button class="btn btn-primary" type="submit" style="height: 40px;">
                                      <i class="fas fa-search"></i>
                                  </button>
                              </div>
                          </div>
                      </form>
                  </div>
                  <div class="col-md-6">
                      @can('Role Create')
                      <a href="{{ route('tags.create') }}" class="btn btn-primary float-right" role="button">
                          Add New

                      </a>
                      @endcan
                  </div>
              </div>
          </div>
          <div class="card-body">
              <ul class="list-group list-group-flush">
                  <!-- card-header -->
                  <div class="table-responsive table-striped">
                      <table class="table mg-b-0 tx-13">
                          <thead>
                              <tr class="tx-10">

                                  <th class="pd-y-5">Name</th>
                                  <th class="pd-y-5 tx-center t-center">Status</th>
                                  <th class="pd-y-5 tx-center t-center">Actions</th>
                              </tr>
                          </thead>
                          <tbody>
                              @forelse ($tags as $tag)
                              <tr>
                                  <td style="width: 80%;" class="valign-middle tx-medium tx-inverse tx-14">
                                      {{ $tag->tag_title }}
                                  </td>

                                  <td style="width: 10%;" class="t-center valign-middle tx-center">
                                      @if ($tag->is_active == 1)
                                      <span class="status-active">Active</span>
                                      @else
                                      <span class="status-nonactive">Non-Active</span>
                                      @endif
                                  </td>

                                  <td style="width: 10%;" class="t-center valign-middle tx-center">
                                      <div class="row" style="margin-left: 0px; margin-right: 0px;">
                                          <!-- <div class="col-md-4">
                                                                                              <a href="{{ route('tags.show', ['tag' => $tag]) }}" class="btn btn-sm btn-primary" role="button">
                                                                                                  <i class="fas fa-eye"></i>
                                                                                              </a>
                                                                                          </div> -->
                                          <div class="col-md-6">
                                              @can('Role Update')
                                              <a href="{{ route('tags.edit', ['tag' => $tag]) }}" class="btn btn-sm btn-info" role="button">
                                                  <i class="fas fa-edit"></i>
                                              </a>
                                              @endcan
                                          </div>
                                          <div class="col-md-6">
                                              @can('Role Delete')
                                              <form class="d-inline" role="alert" action="{{ route('tags.destroy', ['tag' => $tag]) }}" method="POST">
                                                  @csrf
                                                  @method('DELETE')
                                                  <button type="submit" class="btn btn-sm btn-danger">
                                                      <i class="fas fa-trash"></i>
                                                  </button>
                                              </form>
                                              @endcan
                                          </div>
                                      </div>

                                  </td>
                              </tr>
                              @empty
                              <table>

                              </table>
                              <p style="text-align: center; padding-top: 50px;">
                                  @if (request()->get('keyword'))
                                  <strong>Tag not found</strong>
                                  @else
                                  <strong>No Tag data yet</strong>
                                  @endif

                              </p>
                              @endforelse

                          </tbody>
                      </table>
                  </div>
                  <!-- table-responsive -->

              </ul>
          </div>
          <!-- table-responsive -->
          @if ($tags->hasPages())
          <div class="card-footer">
              {{ $tags->links('vendor.pagination.bootstrap-4') }}
          </div>
          @endif
      </div>
  </div>
</div>
@endsection

@push('javascript-internal')
<script>
  $(document).ready(function() {
      $("form[role='alert']").submit(function(event) {
          event.preventDefault();
          Swal.fire({
              title: 'Delete Tag',
              text: 'Are you sure want to remove Tag?',
              icon: 'warning',
              allowOutsideClick: false,
              showCancelButton: true,
              cancelButtonText: "Cancel",
              reverseButtons: true,
              confirmButtonText: "Yes",
          }).then((result) => {
              if (result.isConfirmed) {
                  // todo: process of deleting categories
                  event.target.submit();
              }
          });
      });
  });
</script>
@endpush