routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('dashboard.index');
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');

    Route::get('/password', [App\Http\Controllers\PasswordController::class, 'edit'])->name('password.edit');
    Route::patch('/password', [App\Http\Controllers\PasswordController::class, 'updatePassword'])->name('password.updatePassword');

    //Roles Route
    Route::get('/roles/select', [App\Http\Controllers\RoleController::class, 'select'])->name('roles.select');
    Route::resource('/roles', \App\Http\Controllers\RoleController::class);

    //User Route
    Route::resource('/users', \App\Http\Controllers\UserController::class);

    //Category Post Route
    Route::get('/categories-post/select', [App\Http\Controllers\CategoriesPostController::class, 'select'])->name('categoriespost.select');
    Route::resource('/categories-post', App\Http\Controllers\CategoriesPostController::class);

    //Tag Post Route
    Route::get('/tags/select', [App\Http\Controllers\TagController::class, 'select'])->name('tags.select');
    Route::resource('/tags', App\Http\Controllers\TagController::class);

    //Post Route
    Route::resource('/posts', App\Http\Controllers\PostController::class);

    //File Manager Route 
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
   
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use DigitalCloud\Blameable\Traits\Blameable;

class Post extends Model
{
    use HasFactory;
    protected $table = 'post_posts';
    use Blameable;
    protected $fillable = ['category_id', 'post_title', 'post_slug', 'post_thumbnail', 'post_excerpt', 'post_desc', 'post_meta_title', 'post_meta_description', 'post_meta_keyword', 'is_active', 'article_status'];


    public function scopeSearch($query, $title)
    {
        return $query->where('post_title', 'LIKE', "%{$title}%");
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'post_tag', 'post_id', 'tag_id')->withTimestamps();
    }

    public function category()
    {
        return $this->belongsTo(CategoriesPost::class);
    }

    public function getRouteKeyName()
    {
        return 'post_slug';
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\CategoriesPost;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:Post Show', ['only' => 'index']);
        $this->middleware('permission:Post Create', ['only' => ['create', 'store']]);
        $this->middleware('permission:Post Update', ['only' => ['edit', 'update']]);
        $this->middleware('permission:Post Delete', ['only' => 'destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::with(['category']);

        if ($request->get('category')) {
            $category = $request->category;
            $posts->whereHas(
                'category',
                function ($query) use ($category) {
                    $query->where('category_title', 'LIKE', "%{$category}%");
                }
            );
        } else {
        }

        if ($request->get('keyword')) {
            $posts->search($request->keyword);
        }
        return view('posts.index', [
            'posts' => $posts->orderBy('created_at', 'desc')->paginate(7)->withQueryString(),
            'categoriesPosts' => CategoriesPost::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = CategoriesPost::all();
        $tags = Tag::all();
        $statuses = $this->statuses();
        return view('posts.create', compact('statuses', 'tags', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'post_title' => 'required|string|unique:post_posts,post_title',
            'post_slug' => 'required|string|unique:post_posts,post_slug',
            'post_thumbnail' => 'required',
            'post_excerpt' => 'required|string|max:500',
            'post_desc' => 'required|string',
            'category' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $post = Post::create([
                'category_id' => $request->category,
                'post_title' => $request->post_title,
                'post_slug' => $request->post_slug,
                'post_thumbnail' => parse_url($request->post_thumbnail)['path'],
                'post_excerpt' => $request->post_excerpt,
                'post_desc' => $request->post_desc,
                'post_meta_title' => $request->post_meta_title,
                'post_meta_description' => $request->post_meta_description,
                'post_meta_keyword' => $request->post_meta_keyword,
                'is_active' => ($request->is_active) ? '1' : '0',
                'article_status' => $request->article_status,
                'user_id' => $request->user_id
            ]);
            $post->tags()->attach($request->tag);
            Alert::success('Add Post', 'Added Post Success');
        } catch (\Throwable $th) {
            DB::rollBack();
            //dd($th->getMessage());
        } finally {
            DB::commit();
        }
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $categories = $post->categories;
        $tags = $post->tags;

        return view('posts.show', compact('post', 'categories', 'tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = CategoriesPost::all();

        $statuses = $this->statuses();
        $categorySelected = $post->category;

        //dd($post->category);
        return view('posts.edit', compact('post', 'categorySelected', 'categories', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'post_title' => 'required|string',
                'post_slug' => 'required|string|unique:post_posts,post_slug,' . $post->id,
                'post_thumbnail' => 'required',
                'post_excerpt' => 'required|string|max:500',
                'post_desc' => 'required|string',
                'category' => 'required'
            ],
            [],
        );

        if ($validator->fails()) {
            if ($request['tag']) {
                $request['tag'] = Tag::select('id', 'tag_title')->whereIn('id', $request->tag)->get();
            }
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }
        DB::beginTransaction();
        try {
            $post->update([
                'category_id' => $request->category,
                'post_title' => $request->post_title,
                'post_slug' => $request->post_slug,
                'post_thumbnail' => parse_url($request->post_thumbnail)['path'],
                'post_excerpt' => $request->post_excerpt,
                'post_desc' => $request->post_desc,
                'post_meta_title' => $request->post_meta_title,
                'post_meta_description' => $request->post_meta_description,
                'post_meta_keyword' => $request->post_meta_keyword,
                'is_active' => ($request->is_active) ? '1' : '0',
                'article_status' => $request->article_status,
                'user_id' => $request->user_id
            ]);
            $post->tags()->sync($request->tag);

            Alert::success('Update Post', 'Updated Post Success');
            //dd($request->all());
            return redirect()->route('posts.index');
        } catch (\Throwable $th) {
            DB::rollBack();
            Alert::success('Update Post', 'Updated Post Success', ['error' => $th->getMessage()]);
            if ($request['tag']) {
                $request['tag'] = Tag::select('id', 'tag_title')->whereIn('id', $request->tag)->get();
            }
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        } finally {
            DB::commit();
        }
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        try {
            $post->delete();
            Alert::success('Delete Post', 'Delete Post Success');
        } catch (\Throwable $th) {
            Alert::error('Delete Post', 'Error' . $th->getMessage());
        }
        return redirect()->back();
    }

    private function statuses()
    {
        return [
            '0' => 'Draft',
            '1' => 'Published',
        ];
    }
}

resources/views/posts/index.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
  <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
          {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
          {{ Breadcrumbs::render('posts') }}
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
          <div class="pe-md-3 d-flex align-items-center">
              <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                  <i class='bx bx-log-out'></i>
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                  @csrf
              </form>
          </div>
          <div class="user-setting">
              <div class="imgBox">
                  <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
              </div>
          </div>
      </div>
  </div>
</nav>
@endsection

@section('content')
<div class="row">
  <div class="col-md-12">
      <div class="card">

          <div class="card-header">

              {{-- filter:start --}}
              <form class="row" method="GET">
                  <div class="col-md-2">
                      <select name="category" class="form-control">
                          <option value="" selected>All Category</option>
                          @foreach ($categoriesPosts as $category)
                          <option value="{{ $category->category_title }}" {{ request('category') === $category->category_title ? 'selected' : null }}>
                              {{ $category->category_title }}
                          </option>
                          @endforeach
                      </select>
                  </div>
                  <div class="col-md-4">
                      <input name="keyword" value="{{ request('keyword') }}" type="search" class="form-control" style="height: 43px;" placeholder="Search for post..">
                  </div>
                  <div class="col-md-2">
                      <button type="submit" class="btn btn-primary mb-3">Search</button>
                  </div>
                  <div class="col-md-4">

                      @can('Post Create')
                      <a href="{{ route('posts.create') }}" class="btn btn-primary float-right" role="button">
                          Add New

                      </a>
                      @endcan

                  </div>
              </form>
              {{-- filter:end --}}

          </div>

          <div class="card-body">
              <ul class="list-group list-group-flush">
                  <!-- card-header -->
                  <div class="table-responsive table-striped">
                      <table class="table mg-b-0 tx-13">
                          <thead>
                              <tr class="tx-10">
                                  <th style="width: 20%;" class="pd-y-5">Title</th>
                                  <th style="width: 40%; max-width: 40%" class="pd-y-5">Description</th>
                                  <th style="width: 10%;" class="pd-y-5 tx-center t-center">Category</th>
                                  <th style="width: 10%;" class="pd-y-5 tx-center t-center">Date</th>
                                  <th style="width: 10%;" class="pd-y-5 tx-center t-center">Status</th>
                                  <th style="width: 10%;" class="pd-y-5 tx-center t-center">Actions</th>
                              </tr>
                          </thead>
                          <tbody>
                              @forelse ($posts as $post)
                              <tr>
                                  <td style="width: 20%;" class="pd-y-5 valign-middle tx-medium tx-inverse tx-14">
                                      {{ $post->post_title }}

                                  <td style="width: 40%; max-width: 40%" class="pd-y-5 valign-middle tx-medium tx-inverse tx-14">
                                      {!! $post->post_excerpt !!}
                                  </td>

                                  <td style="width: 10%;" class="pd-y-5 t-center tx-center valign-middle tx-medium tx-inverse tx-14">
                                      {{ $post->category->category_title }}
                                  </td>

                                  <td style="width: 10%;" class="pd-y-5 t-center tx-center valign-middle tx-medium tx-inverse tx-14">
                                      {{ date('d, M Y', strtotime($post->created_at)) }}
                                  </td>

                                  <td style="width: 10%;" class="pd-y-5 t-center valign-middle tx-center">
                                      @if ($post->article_status == 'reviewed')
                                      <span class="status-review">Reviewed</span>
                                      @elseif ($post->article_status == 'rejected')
                                      <span class="status-reject">Rejected</span>
                                      @elseif ($post->article_status == 'published')
                                      <span class="status-publish">Published</span>
                                      @else
                                      <span class="status-draft">Draft</span>
                                      @endif
                                  </td>

                                  <td style="width: 10%;" class="pd-y-5 valign-middle tx-center  t-center">
                                      <div class="row" style="margin-left: 0px; margin-right: 0px;">
                                          <!-- <div class="col-md-4">
                                                                                                                                      <a href="{{ route('posts.show', ['post' => $post]) }}" class="btn btn-sm btn-primary" role="button">
                                                                                                                                          <i class="fas fa-eye"></i>
                                                                                                                                      </a>
                                                                                                                                  </div> -->
                                          <div class="col-md-6">
                                              @can('Post Update')
                                              <a href="{{ route('posts.edit', ['post' => $post]) }}" class="btn btn-sm btn-info" role="button">
                                                  <i class="fas fa-edit"></i>
                                              </a>
                                              @endcan
                                          </div>
                                          <div class="col-md-6">
                                              @can('Post Delete')
                                              <form class="d-inline" role="alert" action="{{ route('posts.destroy', ['post' => $post]) }}" method="POST">
                                                  @csrf
                                                  @method('DELETE')
                                                  <button type="submit" class="btn btn-sm btn-danger">
                                                      <i class="fas fa-trash"></i>
                                                  </button>
                                              </form>
                                              @endcan
                                          </div>
                                      </div>

                                  </td>
                              </tr>
                              @empty
                              <table>

                              </table>
                              <p style="text-align: center; padding-top: 50px;">
                                  @if (request()->get('keyword'))
                                  <strong>Article not found</strong>
                                  @else
                                  <strong>No article data yet</strong>
                                  @endif

                              </p>
                              @endforelse

                          </tbody>
                      </table>
                  </div>
                  <!-- table-responsive -->

              </ul>
          </div>
          <!-- table-responsive -->
          @if ($posts->hasPages())
          <div class="card-footer">
              {{ $posts->links('vendor.pagination.bootstrap-4') }}
          </div>
          @endif
      </div>
  </div>
</div>
@endsection

@push('javascript-internal')
<script>
  $(document).ready(function() {
      $("form[role='alert']").submit(function(event) {
          event.preventDefault();
          Swal.fire({
              title: 'Delete Post',
              text: 'Are you sure want to remove Post?',
              icon: 'warning',
              allowOutsideClick: false,
              showCancelButton: true,
              cancelButtonText: "Cancel",
              reverseButtons: true,
              confirmButtonText: "Yes",
          }).then((result) => {
              if (result.isConfirmed) {
                  // todo: process of deleting categories
                  event.target.submit();
              }
          });
      });
  });
</script>
@endpush