routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ForgotPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('dashboard.index');
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');

    Route::get('/password', [App\Http\Controllers\PasswordController::class, 'edit'])->name('password.edit');
    Route::patch('/password', [App\Http\Controllers\PasswordController::class, 'updatePassword'])->name('password.updatePassword');

    //Roles Route
    Route::get('/roles/select', [App\Http\Controllers\RoleController::class, 'select'])->name('roles.select');
    Route::resource('/roles', \App\Http\Controllers\RoleController::class);

    //User Route
    Route::resource('/users', \App\Http\Controllers\UserController::class);

    //Category Post Route
    Route::get('/categories-post/select', [App\Http\Controllers\CategoriesPostController::class, 'select'])->name('categoriespost.select');
    Route::resource('/categories-post', App\Http\Controllers\CategoriesPostController::class);

    //Tag Post Route
    Route::get('/tags/select', [App\Http\Controllers\TagController::class, 'select'])->name('tags.select');
    Route::resource('/tags', App\Http\Controllers\TagController::class);

    //Post Route
    Route::resource('/posts', App\Http\Controllers\PostController::class);

    //File Manager Route 
    Route::group(['prefix' => 'filemanager'], function () {
        Route::get('/folder', [App\Http\Controllers\FileManagerController::class, 'index'])->name('filemanager.index');
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });
   
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:Role Show', ['only' => 'index']);
        $this->middleware('permission:Role Create', ['only' => ['create', 'store']]);
        $this->middleware('permission:Role Update', ['only' => ['edit', 'update']]);
        $this->middleware('permission:Role Delete', ['only' => 'destroy']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $roles = [];
        if ($request->has('keyword')) {
            $roles = Role::where('name', 'LIKE', "%{$request->keyword}%")->paginate(10);
        } else {
            $roles = Role::paginate(10);
        }
        return view('roles.index', [
            'roles' => $roles->appends(['keyword' => $request->keyword])
        ]);
    }

    public function select(Request $request)
    {
        $roles = Role::select('id', 'name')->limit(7);
        if ($request->has('q')) {
            $roles->where('name', 'LIKE', "%{$request->q}%");
        }

        return response()->json($roles->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create', [
            'authorities' => config('permission.authorities')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'name' => "required|string|max:50|unique:roles,name",
                'permissions' => "required"
            ],
            [],
        );

        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }

        DB::beginTransaction();
        try {
            $role = Role::create(['name' => $request->name]);
            $role->givePermissionTo($request->permissions);
            Alert::success('Add Role', 'Added Role Success');
            return redirect()->route('roles.index');
        } catch (\Throwable $th) {
            DB::rollBack();
            //dd($th->getMessage());
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        } finally {
            DB::commit();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('roles.show', [
            'role' => $role,
            'authorities' => config('permission.authorities'),
            'rolePermissions' => $role->permissions->pluck('name')->toArray()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('roles.edit', [
            'role' => $role,
            'authorities' => config('permission.authorities'),
            'permissionChecked' => $role->permissions->pluck('name')->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'name' => "required|string|max:50|unique:roles,name," . $role->id,
                'permissions' => "required"
            ],
            [],
        );

        if ($validator->fails()) {
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        }

        DB::beginTransaction();
        try {
            $role->name = $request->name;
            $role->syncPermissions($request->permissions);
            $role->save();
            Alert::success('Update Role', 'Updated Role Success');
            return redirect()->route('roles.index');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->withInput($request->all())->withErrors($validator);
        } finally {
            DB::commit();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        if (User::role($role->name)->count()) {
            Alert::warning('Cannot Delete Role', 'Role is used by User');
            return redirect()->route('roles.index');
        }
        DB::beginTransaction();
        try {
            $role->revokePermissionTo($role->permissions->pluck('name')->toArray());
            $role->delete();
            Alert::success('Delete Role', 'Deleted Role Success');
        } catch (\Throwable $th) {
            DB::rollBack();
        } finally {
            DB::commit();
        }

        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
            {{ Breadcrumbs::render('roles') }}
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
            <div class="pe-md-3 d-flex align-items-center">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">
                    <i class='bx bx-log-out'></i>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
            <div class="user-setting">
                <div class="imgBox">
                    <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
                </div>
            </div>
        </div>
    </div>
</nav>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <form action="{{ route('roles.store') }}" method="POST">
                @csrf
                <div class="card-body _card-body">
                    <div class="form-group _form-group">
                        <label for="input_role_name" class="font-weight-bold">
                            Role name
                        </label>
                        <input id="input_role_name" value="{{ old('name') }}" name="name" type="text" class="form-control @error('name') is-invalid @enderror" />
                        @error('name')
                        <span class="invalid-feedback">
                            {{ $message }}
                        </span>
                        @enderror
                    </div>
                    <!-- permission -->
                    <div class="form-group _form-group">
                        <label for="input_role_permission" class="font-weight-bold">
                            Permission
                        </label>
                        <div class="form-control overflow-hidden h-100 @error('permissions') is-invalid @enderror" id="input_role_permission" style="padding: 30px;">
                            <div class="row">
                                <!-- list manage name:start -->
                                @foreach ($authorities as $manageName => $permissions)
                                <div class="col-md-2" style="margin-bottom: 30px;">
                                    <ul class="list-group mx-1">
                                        <li class="list-group-item bg-dark text-white">
                                            {{ $manageName }}
                                        </li>
                                        <!-- list permission:start -->
                                        @foreach ($permissions as $permission)
                                        <li class="list-group-item">
                                            <div class="form-check">
                                                @if (old('permissions'))
                                                <input id="{{ $permission }}" name="permissions[]" class="form-check-input" type="checkbox" value="{{ $permission }}" {{ in_array($permission, old('permissions')) ? "Checked" : null }}>
                                                @else
                                                <input id="{{ $permission }}" name="permissions[]" class="form-check-input" type="checkbox" value="{{ $permission }}">
                                                @endif
                                                <label for="{{ $permission }}" class="form-check-label">
                                                    {{ $permission }}
                                                </label>
                                            </div>
                                        </li>
                                        @endforeach
                                        <!-- list permission:end -->
                                    </ul>
                                </div>

                                <!-- list manage name:end  -->
                                @endforeach
                            </div>
                        </div>
                        @error('permissions')
                        <span class="invalid-feedback">
                            {{ $message }}
                        </span>
                        @enderror
                    </div>
                    <div class="float-right mb-4">
                        <a class="btn btn-outline-secondary _btn-secondary px-4 mx-2" href="{{ route('roles.index') }}">
                            Back
                        </a>
                        <button type="submit" class="btn btn-primary _btn-primary px-4">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
            {{ Breadcrumbs::render('edit_role', $role) }}
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
            <div class="pe-md-3 d-flex align-items-center">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">
                    <i class='bx bx-log-out'></i>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
            <div class="user-setting">
                <div class="imgBox">
                    <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
                </div>
            </div>
        </div>
    </div>
</nav>
@endsection
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <form action="{{ route('roles.update', ['role' => $role]) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body _card-body">
                    <div class="form-group _form-group">
                        <label for="input_role_name" class="font-weight-bold">
                            Role name
                        </label>
                        <input id="input_role_name" value="{{ old('name', $role->name) }}" name="name" type="text" class="form-control @error('name') is-invalid @enderror" />
                        @error('name')
                        <span class="invalid-feedback">
                            {{ $message }}
                        </span>
                        @enderror
                    </div>
                    <!-- permission -->
                    <div class="form-group _form-group">
                        <label for="input_role_permission" class="font-weight-bold">
                            Permission
                        </label>
                        <div class="form-control overflow-hidden h-100 @error('permissions') is-invalid @enderror" id="input_role_permission" style="padding: 30px;">
                            <div class="row">
                                <!-- list manage name:start -->
                                @foreach ($authorities as $manageName => $permissions)
                                <div class="col-md-2" style="margin-bottom: 30px;">
                                    <ul class="list-group mx-1">
                                        <li class="list-group-item bg-dark text-white">
                                            {{ $manageName }}
                                        </li>
                                        <!-- list permission:start -->
                                        @foreach ($permissions as $permission)
                                        <li class="list-group-item">
                                            <div class="form-check">
                                                @if (old('permissions', $permissionChecked))
                                                <input id="{{ $permission }}" name="permissions[]" class="form-check-input" type="checkbox" value="{{ $permission }}" {{ in_array($permission, old('permissions', $permissionChecked)) ? "Checked" : null }}>
                                                @else
                                                <input id="{{ $permission }}" name="permissions[]" class="form-check-input" type="checkbox" value="{{ $permission }}">
                                                @endif
                                                <label for="{{ $permission }}" class="form-check-label">
                                                    {{ $permission }}
                                                </label>
                                            </div>
                                        </li>
                                        @endforeach
                                        <!-- list permission:end -->
                                    </ul>
                                </div>


                                <!-- list manage name:end  -->
                                @endforeach
                            </div>
                        </div>
                        @error('permissions')
                        <span class="invalid-feedback">
                            {{ $message }}
                        </span>
                        @enderror
                    </div>
                    <div class="float-right mb-4">
                        <a class="btn btn-outline-secondary _btn-secondary px-4 mx-2" href="{{ route('roles.index') }}">
                            Back
                        </a>
                        <button type="submit" class="btn btn-primary _btn-primary px-4">
                            Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.dashboard')

@section('navbar')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl navbar-custom" id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            {{-- <h6 class="font-weight-bolder mb-0 text-white">Dashboard</h6> --}}
            {{ Breadcrumbs::render('roles') }}
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 logout-icon" id="navbar">
            <div class="pe-md-3 d-flex align-items-center">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">
                    <i class='bx bx-log-out'></i>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
            <div class="user-setting">
                <div class="imgBox">
                    <img src="{{ asset('images/placeholder/user.jpg') }}" alt="">
                </div>
            </div>
        </div>
    </div>
</nav>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{ route('roles.index') }}" method="GET">
                            <div class="input-group">
                                <input name="keyword" value="{{ request()->get('keyword') }}" type="search" class="form-control" style="height: 40px;" placeholder="Search for roles">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit" style="height: 40px;">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        @can('Role Create')
                        <a href="{{ route('roles.create') }}" class="btn btn-primary float-right" role="button">
                            Add New

                        </a>
                        @endcan
                    </div>
                </div>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <!-- card-header -->
                    <div class="table-responsive table-striped">
                        <table class="table mg-b-0 tx-13">
                            <thead>
                                <tr class="tx-10">
                                    <th class="pd-y-5">Roles</th>

                                    <th class="pd-y-5 tx-center t-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($roles as $role)
                                <tr>
                                    <td style="width: 90%;" class="valign-middle tx-medium tx-inverse tx-14">
                                        {{ $role->name }}
                                    </td>

                                    <td style="width: 10%;" class="valign-middle tx-center t-center">
                                        <div class="row" style="margin-left: 0px; margin-right: 0px;">
                                            <!-- <div class="col-md-4">
                                                        <a href="{{ route('roles.show', ['role' => $role]) }}" class="btn btn-sm btn-primary" role="button">
                                                            <i class="fas fa-eye"></i>
                                                        </a>
                                                    </div> -->
                                            <div class="col-md-6">
                                                @can('Role Update')
                                                <a href="{{ route('roles.edit', ['role' => $role]) }}" class="btn btn-sm btn-info" role="button">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                @endcan
                                            </div>
                                            <div class="col-md-6">
                                                @can('Role Delete')
                                                <form class="d-inline" role="alert" action="{{ route('roles.destroy', ['role' => $role]) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-danger">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </form>
                                                @endcan
                                            </div>
                                        </div>

                                    </td>
                                </tr>
                                @empty
                                <table>

                                </table>
                                <p style="text-align: center; padding-top: 50px;">
                                    @if (request()->get('keyword'))
                                    <strong>Roles not Found</strong>

                                    @else
                                    <strong>No Roles data yet</strong>
                                    @endif

                                </p>
                                @endforelse

                            </tbody>
                        </table>
                    </div>
                    <!-- table-responsive -->
                    @if ($roles->hasPages())
                    <div class="card-footer">
                        {{ $roles->links('vendor.pagination.bootstrap-4') }}
                    </div>
                    @endif
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection

@push('javascript-internal')
<script>
    $(document).ready(function() {
        $("form[role='alert']").submit(function(event) {
            event.preventDefault();
            Swal.fire({
                title: 'Delete Banner',
                text: 'Are you sure want to remove Banner?',
                icon: 'warning',
                allowOutsideClick: false,
                showCancelButton: true,
                cancelButtonText: "Cancel",
                reverseButtons: true,
                confirmButtonText: "Yes",
            }).then((result) => {
                if (result.isConfirmed) {
                    // todo: process of deleting categories
                    event.target.submit();
                }
            });
        });
    });
</script>
@endpush

resources/views/roles/show.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="home-section">
    {{ Breadcrumbs::render('detail_role', $role) }}

    <div class="text">
        @section('title')
        Detail Roles
        @endsection
        Detail Roles
    </div>

    <!-- content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="input_role_name" class="font-weight-bold">
                                Role name
                            </label>
                            <input id="input_role_name" value="{{ $role->name }}" name="name" type="text" class="form-control" readonly />
                        </div>
                        <!-- permission -->
                        <div class="form-group">
                            <label for="input_role_permission" class="font-weight-bold">
                                Permission
                            </label>
                            <div class="row">
                                <!-- list manage name:start -->
                                @forelse ($authorities as $manageName => $permissions)
                                <ul class="list-group mx-1">
                                    <li class="list-group-item bg-dark text-white">
                                        {{ $manageName }}
                                    </li>

                                    @foreach ($permissions as $permission)
                                    <!-- list permission:start -->
                                    <li class="list-group-item">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" onclick="return false;" {{ in_array($permission, $rolePermissions) ? 'checked' : null }}>
                                            <label class="form-check-label">
                                                {{ $permission }}
                                            </label>
                                        </div>
                                    </li>
                                    <!-- list permission:end -->
                                    @endforeach
                                </ul>
                                @empty
                                <table>

                                </table>
                                <p style="text-align: center; padding-top: 50px;">
                                    <strong>No Permissions data yet</strong>
                                </p>
                                @endforelse

                                <!-- list manage name:end  -->
                            </div>
                        </div>
                        <!-- button  -->
                        <div class="d-flex justify-content-end">
                            <a href="{{ route('roles.index') }}" class="btn btn-primary mx-1" role="button">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</section>
@endsection